### Question 1: Write a function that takes two sets as input and returns their union.
- `Sample Input: set1 = {1, 2, 3}, set2 = {3, 4, 5}`
- `Sample Output: {1, 2, 3, 4, 5}`

In [4]:
def union_of_sets(set1, set2):
    return set1.union(set2)
set1 = {1, 2, 3}
set2 = {3, 4, 5}
result = union_of_sets(set1, set2)
print(result)

{1, 2, 3, 4, 5}

### Question 2: Write a function that takes two sets as input and returns their intersection.

   - `Sample Input: set1 = {1, 2, 3}, set2 = {3, 4, 5}`
   - `Sample Output: {3}`

In [9]:
def intersection(set1, set2):
    return set1.intersection(set2)
set1 = {1, 2, 3}
set2 = {3, 4, 5}
result = intersection(set1, set2)
print(result)

{3}

### Question 3:  Write a function that takes two sets as input and returns the elements that are in the first set but not in the second set.
- `Sample Input: set1 = {1, 2, 3}, set2 = {3, 4, 5}`
- `Sample Output: {1, 2}`

In [8]:
def difference(set1, set2):
    return set1.difference(set2)
set1 = {1, 2, 3}
set2 = {3, 4, 5}
result = difference(set1, set2)
print(result)

{1, 2}

### Question 4: Write a function that checks if one set is a subset of another set.
   - `Sample Input: set1 = {1, 2, 3}, set2 = {1, 2, 3, 4, 5}`
   - `Sample Output: True`

In [10]:
def is_subset(set1, set2):
    return set1.issubset(set2)
set1 = {1, 2, 3}
set2 = {1, 2, 3, 4, 5}
result = is_subset(set1, set2)
print(result)

True

### Question 5: Write a function that returns the symmetric difference between two sets.

   - `Sample Input: set1 = {1, 2, 3, 4}, set2 = {3, 4, 5, 6}`
   - `Sample Output: {1, 2, 5, 6}`

In [11]:
def symmetric_difference(set1, set2):
    return set1.symmetric_difference(set2)
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
result = symmetric_difference(set1, set2)
print(result)

{1, 2, 5, 6}

### Question 6:  Write a function that takes a universal set and a subset as input and returns the complement of the subset.

   - `Sample Input: universal_set = {1, 2, 3, 4, 5}, subset = {3, 4}`
   - `Sample Output: {1, 2, 5}`

In [12]:
def complement(universal_set, subset):
    return universal_set.difference(subset)
universal_set = {1, 2, 3, 4, 5}
subset = {3, 4}
result = complement(universal_set, subset)
print(result)

{1, 2, 5}

### Question 7 : Write a function that returns the number of elements in a set.

   - `Sample Input: my_set = {10, 20, 30, 40, 50}`
   - `Sample Output: 5`

In [14]:
def count_elements(my_set):
    return len(my_set)
my_set = {10, 20, 30, 40, 50}
result = count_elements(my_set)
print(result)

5

### Question 8 : Write a function that returns the sum of all elements in a set of numbers.

   - `Sample Input: num_set = {2, 4, 6, 8, 10}`
   - `Sample Output: 30`

In [15]:
def sum_of_elements(num_set):
    total = 0
    for num in num_set:
        total += num
    return total
num_set = {2, 4, 6, 8, 10}
result = sum_of_elements(num_set)
print(result)

30

In [17]:
def sum_of_elements(num_set):
    return sum(num_set)
num_set = {2, 4, 6, 8, 10}
result = sum_of_elements(num_set)
print(result)

30


### Question 9 : Write a function that returns the size of the intersection between two sets.

   - `Sample Input: set1 = {1, 2, 3, 4}, set2 = {3, 4, 5, 6}`
   - `Sample Output: 2`

In [18]:
def intersection_size(set1, set2):
    count = 0
    for element in set1:
        if element in set2:
            count += 1
    return count
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
result = intersection_size(set1, set2)
print(result)

2

### Question 10:Write a function that generates the powerset of a given set (all possible subsets).

- `Sample Input: my_set = {1, 2}`
- `Sample Output: {{}, {1}, {2}, {1, 2}}`

In [30]:
def powerset(my_set):
    set_list = list(my_set)
    powerset_result = [[]]

    for element in set_list:
        powerset_result += [subset + [element] for subset in powerset_result]
    return [set(subset) for subset in powerset_result]
my_set = {1, 2}
result = powerset(my_set)
print(result)

[set(), {1}, {2}, {1, 2}]