### Question 1: Write a Python program to create an empty tuple.


- `sample input : `
    - `var = (10,11,15,20)`
- `sample output :`
    - `result :()`

In [62]:
var = (10, 11, 15, 20)
result = ()
print(result)

()

### Question 2: Write a Python program to access the elements of a tuple.

- `sample input : `
    - `var = (10,15,20,40,55)`
- `sample output :`
    - `result : Access using Techniques available ex: 20 can be accessed with there memory allocation `

In [64]:
var = (10, 15, 20, 40, 55)
print(var[2])

20

### Question 3: Write a Python program to concatenate two tuples.

Sample Input 1:

    Tuple 1: (1, 2, 3)
    Tuple 2: (4, 5, 6)

Sample Output 1:

    Concatenated Tuple: (1, 2, 3, 4, 5, 6)

Sample Input 2:

    Tuple 1: ("apple", "banana")
    Tuple 2: ("cherry", "date")

Sample Output 2:

    Concatenated Tuple: ("apple", "banana", "cherry", "date")

In [6]:
t1 = (1, 2, 3)
t2 = (4, 5, 6)
concatenated_tuple = t1 + t2
print("Concatenated Tuple:", concatenated_tuple)
t3 = ("apple", "banana")
t4 = ("cherry", "date")
concatenated_tuple = t3 + t4
print("Concatenated Tuple:", concatenated_tuple)

Concatenated Tuple: (1, 2, 3, 4, 5, 6)
Concatenated Tuple: ('apple', 'banana', 'cherry', 'date')

### Question 4: Write a Python program to access the first and last elements of a tuple.

- `Sample Input: (1, 2, 3, 4, 5)`


- `Sample Output: First Element: 1, Last Element: 5`

In [11]:
tuple = (1, 2, 3, 4, 5)
first_element = tuple[0]
last_element = tuple[4]
print(f"First Element: {first_element}, Last Element: {last_element}")

First Element: 1, Last Element: 5

### Question 5: Write a Python program to reverse a tuple.

- `Sample Input: (5, 4, 3, 2, 1)`
- `Sample Output: (1, 2, 3, 4, 5)`

In [28]:
tuple= (5, 4, 3, 2, 1)
reversed_tuple = len(tuple) * [0]
for i in range(len(tuple)):
    reversed_tuple[i] = tuple[len(tuple) - i - 1]
print("Reversed Tuple:", reversed_tuple)

Reversed Tuple: [1, 2, 3, 4, 5]

### Question 6: Write a Python program to find the maximum and minimum elements of a tuple.

- `Sample Input: (15, 25, 10, 30, 20)`
- `Sample Output: Maximum: 30, Minimum: 10`

In [57]:
y= (15, 25, 10, 30, 20)
maximum = max(y)
minimum = min(y)
print("Maximum:", maximum)
print("Minimum:", minimum)

Maximum: 30
Minimum: 10

### Question 7: Write a Python program to remove an element from a tuple.

- `Sample Input: (1, 2, 3, 4, 5), 3`
- `Sample Output: (1, 2, 4, 5)`

In [60]:
a= (1, 2, 3, 4, 5)
b= 3
for i in range(len(a)):
    if a[i] == b:
        a = a[:i] + a[i+1:]
        break
print(a)

(1, 2, 4, 5)

### Question 8: Write a Python program to convert a list of tuples into a dictionary.

- `Sample Input: [(1, "one"), (2, "two"), (3, "three")]`
- `Sample Output: {1: 'one', 2: 'two', 3: 'three'}`

In [49]:
x = [(1, "one"), (2, "two"), (3, "three")]
y = dict(x)
print(y)

{1: 'one', 2: 'two', 3: 'three'}

### Question 9: Write a Python program to find the intersection of two tuples.

- `Sample Input: (1, 2, 3, 4, 5), (4, 5, 6, 7, 8)`
- `Sample Output: (4, 5)`

In [55]:
x= (1, 2, 3, 4, 5)
y= (4, 5, 6, 7, 8)
z= set(x) & set(y)
print(z)

{4, 5}

### Question 10: Write a Python program to sort a tuple of tuples by the second element of each tuple.

- `Sample Input: ((1, 5), (3, 2), (2, 7), (4, 6))`
- `Sample Output: ((3, 2), (1, 5), (4, 6), (2, 7)`

In [67]:
a= ((1, 5), (3, 2), (2, 7), (4, 6))
b= sorted(a, key=lambda x: x[1])
print(b)

[(3, 2), (1, 5), (4, 6), (2, 7)]